import { expect, test } from '@playwright/test'

test('a customer updates their name from the profile page', async ({ page }) => {
  await page.goto('/account/profile')
  await expect(page).toHaveURL(/\/sign-in\?returnTo=.*account%2Fprofile/)
  await page.getByRole('link', { name: 'Create an account' }).click()
  await page.getByLabel('Full name').fill('Ada Reader')
  await page.getByLabel('Email address').fill('profile@example.com')
  await page.getByLabel('Password').fill('bookstore-password-123')
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page.getByRole('heading', { name: 'Your profile' })).toBeVisible()
  await expect(page.getByText('profile@example.com')).toBeVisible()
  await expect(page.getByLabel('Email address')).toHaveCount(0)
  await page.getByLabel('Full name').fill('Ada Updated')
  await page.getByRole('button', { name: 'Save name' }).click()
  await expect(page.getByText('Name updated.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Account', exact: true }).click()
  await expect(page.getByText('Ada Updated', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByLabel('New password', { exact: true }).fill('short')
  await page.getByLabel('Confirm new password').fill('short')
  await page.getByRole('button', { name: 'Change password' }).click()
  await expect(page.getByText('Enter your current password.')).toBeVisible()
  await page.getByLabel('Current password').fill('bookstore-password-123')
  await page.getByLabel('New password', { exact: true }).fill('short')
  await page.getByRole('button', { name: 'Change password' }).click()
  await expect(page.getByText('Use at least 8 characters.')).toBeVisible()
})
