import { expect, test } from '@playwright/test'

test('desktop sidebar collapses, preserves navigation and search, and restores its preference', async ({
  page,
  request,
}) => {
  expect((await request.post('http://localhost:4100/__test__/seed-demo')).ok()).toBe(true)
  await page.goto('/sign-in')
  await page.getByRole('button', { name: 'Demo Admin', exact: true }).click()
  await expect(page).toHaveURL('/admin')
  const sidebar = page.locator('[data-slot="sidebar"][data-state]')
  await expect(sidebar).toHaveAttribute('data-state', 'expanded')
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click()
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  const navigation = page.getByRole('navigation', { name: 'Admin navigation' })
  const books = navigation.getByRole('link', { name: 'Books', exact: true })
  await books.hover()
  await expect(page.getByRole('tooltip')).toHaveText('Books')
  await books.click()
  await expect(page).toHaveURL('/admin/books')
  await expect(books).toHaveAttribute('aria-current', 'page')
  await page.getByRole('button', { name: 'Search workspace', exact: true }).click()
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await page.getByRole('button', { name: 'Close dialog', exact: true }).focus()
  await page.keyboard.press('Control+b')
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await page.getByRole('combobox').press('Escape')
  await page.reload()
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await page.screenshot({ path: 'test-results/admin-sidebar-collapsed.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  const menu = page.getByRole('button', { name: 'Admin menu', exact: true })
  await menu.click()
  await expect(page.getByRole('dialog', { name: 'Sidebar' })).toBeVisible()
  await navigation.getByRole('link', { name: 'Order requests', exact: true }).click()
  await expect(page).toHaveURL('/admin/orders')
  await expect(page.getByRole('dialog', { name: 'Sidebar' })).toHaveCount(0)
  await page.setViewportSize({ width: 1280, height: 900 })
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await page.getByRole('button', { name: 'Expand sidebar', exact: true }).click()
  await expect(sidebar).toHaveAttribute('data-state', 'expanded')
  await page.reload()
  await expect(sidebar).toHaveAttribute('data-state', 'expanded')
  await page.getByRole('textbox', { name: 'Search orders' }).focus()
  await page.keyboard.press('Control+b')
  await expect(sidebar).toHaveAttribute('data-state', 'expanded')
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).focus()
  await page.keyboard.press('Control+b')
  await expect(sidebar).toHaveAttribute('data-state', 'collapsed')
  await page
    .context()
    .addCookies([{ name: 'sidebar_state', value: 'invalid', url: 'http://localhost:4173' }])
  await page.reload()
  await expect(sidebar).toHaveAttribute('data-state', 'expanded')
})
